services:
  db:
    container_name: postgresql
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasius
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./back-end
    container_name: backend
    restart: always
    volumes:
      - ./back-end:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tasius?schema=learn
      PORT: 3000
    command: sh -c "npx prisma migrate dev --name init && npm run prisma:seed && npm run dev"

  frontend:
    build: ./front-end
    container_name: frontend
    volumes:
      - ./front-end:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3000/api

volumes:
  postgres_data:
